[package]
name = "nimbus_ai"
version = "0.1.0"
edition = "2021"

[dependencies]
# Add your dependencies here, for example:
# serde = { version = "1.0", features = ["derive"] }
# tokio = { version = "1", features = ["full"] }

[lib]
crate-type = ["cdylib", "rlib"]